base_url: "https://the-internet.herokuapp.com"
browsers:
  - name: "chrome"
    headless: True
#  - name: "firefox"
#    headless: False
#  - name: "chrome"
#    headless: True
#  - name: "firefox"
#    headless: True