name: Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyyaml behave-html-reporter



      - name: Run Selenium tests and generate HTML report
        env:
          ENVIRONMENT: dev
        run: |
          behave features/ --format html --outfile reports/behave_report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: Behave-HTML-Report
          path: reports/behave_report.html
