name: Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install -y xvfb

      - name: Run Selenium tests and generate Allure report
        env:
          ENVIRONMENT: dev
        run: |
          xvfb-run --auto-servernum behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results --tags=@Regression

      - name: Set up virtual display
        run: Xvfb :99 -screen 0 1920x1080x24 &
      - name: Set DISPLAY environment variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Results
          path: reports/allure-results

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Report
          path: reports/allure-report
